spring:
  application:
    name: spring-graphql
  graphql:
    schema:
      locations: classpath:graphql
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update